### ISSUE TITLE
gallery not working.

### ISSUE THREAD

**Issue by danielpmc** [TannerReynolds/ShareX-Upload-Server#25]
**Describe the bug**
gallery doesnt work. Just tries to load then fails after about 2 - 3mins

**To Reproduce**
Just run the latest version of this and try and access the gallery

**Expected behavior**
To show screenshots, etc

**ShareS Version**
Latest

**Desktop (please complete the following information):**
 - OS: Windows 10 (Will all latest updates)
 - Browser Google Chrome
 - Version 80.0.3987.132

**Comment by 2MPP** [comment]
> 
> 
> **Describe the bug**
> gallery doesnt work. Just tries to load then fails after about 2 - 3mins
> 
> **To Reproduce**
> Just run the latest version of this and try and access the gallery
> 
> **Expected behavior**
> To show screenshots, etc
> 
> **ShareS Version**
> Latest
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 10 (Will all latest updates)
> 
>     * Browser Google Chrome
> 
>     * Version 80.0.3987.132

I have the same issues 
  **ShareS Version**
   latest

 **Desktop (please complete the following information):**

    * OS: windows 10
 
     * Browser: firefox
 
     * Version 74.0 (64 bit)

**Comment by C0braD3v** [comment]
I can also reproduce

**Comment by TannerReynolds** [comment]
Thank you guys, I will look into this immediately!

**Comment by 2MPP** [comment]
if you look more into this any password will ""unlock"" the gallery even if its right or wrong

**Comment by TannerReynolds** [comment]
> if you look more into this any password will ""unlock"" the gallery even if its right or wrong

Wow that is horrifying lol, I'll get on this right after work, so in a few hours

**Comment by TannerReynolds** [comment]
> if you look more into this any password will ""unlock"" the gallery even if its right or wrong

So this is the issue im tackling firstly, and im running latest atm. This is what I got after attempting to access the gallery and it didn't work with the wrong password.
![nw](https://i.imgur.com/3eiEQoK.png)
The gallery not opening at all is what im looking into rn and im running into the same issue, this will be fixed soon!

**Comment by 2MPP** [comment]
Alright i see what the issue @TannerReynolds if you set it to public no matter what password is put in it says it is correct but when its not public its denies it

**Comment by TannerReynolds** [comment]
> Alright i see what the issue @TannerReynolds if you set it to public no matter what password is put in it says it is correct but when its not public its denies it

Ah, thank you. I'm not exactly sure if that's intentional or not but if it were intentional i'd have probably removed the password field for the gallery page. It's a simple fix I'll go ahead and make the Gallery always require a password. Thank you!

**Comment by 2MPP** [comment]
np

**Comment by TannerReynolds** [comment]
[Both of these issues have been fixed!](https://github.com/TannerReynolds/ShareX-Upload-Server/commit/25807c09b468f4b0dbddf9892881feff252281dd)
