### ISSUE TITLE
Random crashes and errors

### ISSUE THREAD

**Issue by C0braD3v** [TannerReynolds/ShareX-Upload-Server#26]
The process randomly crashed, and threw this err:

```js
3|i.smc.wt | TypeError: Cannot read property 'get' of undefined
3|i.smc.wt |     at Shard.wsEvent (/root/projects/i.smc.wtf/node_modules/eris/lib/gateway/Shard.js:433:48)
3|i.smc.wt |     at Shard.onWSMessage (/root/projects/i.smc.wtf/node_modules/eris/lib/gateway/Shard.js:1721:26)
3|i.smc.wt |     at WebSocket.ws.onmessage (/root/projects/i.smc.wtf/node_modules/eris/lib/gateway/Shard.js:1598:33)
3|i.smc.wt |     at WebSocket.onMessage (/root/projects/i.smc.wtf/node_modules/ws/lib/event-target.js:120:16)
3|i.smc.wt |     at WebSocket.emit (events.js:197:13)
3|i.smc.wt |     at Receiver.receiverOnMessage (/root/projects/i.smc.wtf/node_modules/ws/lib/websocket.js:720:20)
3|i.smc.wt |     at Receiver.emit (events.js:197:13)
3|i.smc.wt |     at Receiver.dataMessage (/root/projects/i.smc.wtf/node_modules/ws/lib/receiver.js:414:14)
3|i.smc.wt |     at Receiver.getData (/root/projects/i.smc.wtf/node_modules/ws/lib/receiver.js:346:17)
3|i.smc.wt |     at Receiver.startLoop (/root/projects/i.smc.wtf/node_modules/ws/lib/receiver.js:133:22)
```

**Comment by TannerReynolds** [comment]
Thank you, this looks like a Discord Bot error, I'll look into this immediately

**Comment by C0braD3v** [comment]
Definitely an error with the “logging” bot, I’m not too sure how Eris works, otherwise id make a PR if it was in discord.js

**Comment by C0braD3v** [comment]
Just an Update, the upload server constantly restarts with PM2 causing ram to skyrocket.. log says “Gracefully exiting...”

**Comment by TannerReynolds** [comment]
hmmmmm, I'm gonna need some more info on both of those issues. What exactly is happening at the time of these crashes? I haven't experienced either of these issues on my end

**Comment by C0braD3v** [comment]
Very sorry, this was actually an issue with my pm2 (had is restart when the files updated, and obviously the files change pretty often). However, the original error (from eris) is still present

**Comment by TannerReynolds** [comment]
Hmmmmmm. Can you try to run some commands and see if perhaps a command is causing this issue? Its just very odd that this error would have much at all to do with the bot side of things, and the only spot where I can see it going wrong is in the command files

**Comment by C0braD3v** [comment]
This issue causes the bot not to start, so can’t really run any commands

**Comment by TannerReynolds** [comment]
Hmmmm this is an odd one, I haven't ran into this issue and from my experience with other users, they don't experience this issue. Can you please post your config file while redacting sensitive information, but keeping the syntax? Like `key: ["FakeKey"]`
Thank you

**Comment by C0braD3v** [comment]
Seems after pulling newest version the error no longer occurs. 
Closing
