### ISSUE TITLE
ipban dosnt work :(

### ISSUE THREAD

**Issue by 2MPP** [TannerReynolds/ShareX-Upload-Server#27]
**Describe the bug**
ipbanning people dosnt work

**To Reproduce**
1. go to discord with the bot
2. use the ipban command on a ip
3. bot responds but the ip can still use uploader

**Expected behavior**
user cant use the uploader

**ShareS Version**
latest

**Screenshots**
(IPbanning)
https://ss.2mpcraft.xyz/998GiZtx
(after you get ip banned)
https://ss.2mpcraft.xyz/fJqSFD3z.gif

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 74.0 (64 bit)

**Comment by danielpmc** [comment]
Yup. Same problem here.

**Comment by TannerReynolds** [comment]
Hmmmmm using latest version I cannot replicate this issue unless I use an IPV4 address instead of an IPV6 address. Look at the upload monitor after a banned user uploads to the service, and then take a look and see if the IP you're banning is the same IP that's uploading, it may be using a different protocol (ipv6)

**Comment by TannerReynolds** [comment]
So, after speaking to you, this issue doesn't seem like an issue with the IP ban command itself, but rather, the way the server defines IP addresses coming in. In your case, the server is taking two different IP addresses, and joining them with a comma, and that is why you are having the problem that you're having. I have just updated the dev branch, [so please update your ShareS instance to reflect these changes, and let me know how it goes!](https://github.com/TannerReynolds/ShareX-Upload-Server/commit/001850910dd3d6ea18986fa2c9fcf791f019d2b5)

**Comment by danielpmc** [comment]
Hey sorry for the slow reply. i will try this and let you know

**Comment by TannerReynolds** [comment]
Closing this due to a different approach being taken with this project
