### ISSUE TITLE
Add support for apach2 reverse proxy

### ISSUE THREAD

**Issue by Dennisschu** [TannerReynolds/ShareX-Upload-Server#28]
Could you pls add support for an apache2 reverse proxy?

**Comment by TannerReynolds** [comment]
It should work with Apache 2 reverse proxy. I don't use Apache 2 reverse proxy so I'll probably not get around to this, but it should work, granted you're setting it up similarly to how you would set it up with an Nginx reverse proxy. Make sure it's forwarding everything ShareS needs and it should be good

**Comment by TannerReynolds** [comment]
This is more likely to be an issue with your Apache reverse proxy setup, rather than a ShareS issue
