### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by ChloeFace** [TannerReynolds/ShareX-Upload-Server#29]
**Describe the bug**
Process gives error:

ShareS > TypeError: Cannot read property 'log' of undefined
ShareS >     at process.<anonymous> (/home/chloe/ShareX-Upload-Server/src/index.js:43:54)
ShareS >     at process.emit (events.js:322:22)
ShareS >     at processPromiseRejections (internal/process/promises.js:209:33)
ShareS >     at processTicksAndRejections (internal/process/task_queues.js:98:32)

Continuously

**To Reproduce**
This happens when I start the app through pm2

**Expected behavior**
I expected the service to start, and the web server to be available

I am unable to load the web page

**ShareS Version**
4.5.2 running on Ubuntu 16.04 LTS

**Comment by TannerReynolds** [comment]
This is a non error, you need to ensure your configuration file is setup correctly

**Comment by TannerReynolds** [comment]
Closed due to inactivity
