### ISSUE TITLE
Gallery Admin Key Refused

### ISSUE THREAD

**Issue by Hamster-0001** [TannerReynolds/ShareX-Upload-Server#40]
**Describe the bug**
When attempting to access the gallery using the admin key. It returns unauthorized.

**To Reproduce**
1. Install latest version of the repo
2. Configure server settings
3. Configure admin key
4. Start server
5. Go to yourdomain.com/gallery
6. Input admin key

**Expected behavior**
When inputting a valid admin key, it should return the gallery page

**ShareS Version**
v4.5.3

**Screenshots**
https://cdn.sigmabot.xyz/lTW7pL

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 77.0.1

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
None

**Comment by TannerReynolds** [comment]
Will fix soon

**Comment by 4nt0n10M4** [comment]
I fixed this problem on #41 waiting for the merge :)

**Comment by TannerReynolds** [comment]
https://github.com/TannerReynolds/ShareX-Upload-Server/commit/a8110e78823387a245c970ebfc279ba300562430
