### ISSUE TITLE
Dockerfile wrong

### ISSUE THREAD

**Issue by sinncraft** [TannerReynolds/ShareX-Upload-Server#53]
Hey,

The docker file is wrong currently it is

> FROM node:alpine
> 
> WORKDIR /usr/src/app
> COPY src/ package.json .
> 
> RUN apk --no-cache add exiftool && \
>     npm i
> 
> EXPOSE 80 443
> CMD ["node", "index.js"]

And to get it working had to change it to:

> FROM node:alpine
> 
> WORKDIR /usr/src/app
> COPY src/ package.json /usr/src/app/
> 
> RUN apk --no-cache add exiftool && \
>     npm i
> 
> EXPOSE 80 443
> CMD ["node", "index.js"]

Also you have the docker command as `docker built` instead of `docker build`

Other then that it works great except the discord bot seems to stop working after around an hour, to replicate that just set it up as you say and then let it run for a while and it will throw an error in console or pm2 whichever, to fix this I restart my docker container every 30 mins

**Comment by TannerReynolds** [comment]
https://github.com/TannerReynolds/ShareX-Upload-Server/commit/f5c763b6dc2228212beec03cfe83606c5d283338
