### ISSUE TITLE
Background of .txt files makes it almost unreadable

### ISSUE THREAD

**Issue by LuisVervaet** [TannerReynolds/ShareX-Upload-Server#62]
**Is your feature request related to a problem? Please describe.**
When looking at a txt file [Click Me!](https://cdn.luisvervaet.dev/HMXvR) its almost impossible to read it due to gray on black text. But the issue doesn't happen for .md files. [Example](https://cdn.luisvervaet.dev/DeZO)

**Describe the solution you'd like**
Make .txt files like .md files. (Readable)

**Describe alternatives you've considered**
Color Picker for Theme and or background colors

**Comment by TannerReynolds** [comment]
This sounds like your web browser that is creating that background. For me, the background is white and the text is black. Unfortunately, the text is not an html file, it is a text file that is being rendered by the web browser, the webserver does not send any style information for it.

**Comment by LuisVervaet** [comment]
Yeah I figured it out by deleted some lines of code.
