### ISSUE TITLE
404 error on /api/files

### ISSUE THREAD

**Issue by somerandomcloud** [TannerReynolds/ShareX-Upload-Server#67]
**Describe the bug**
Hey! I wanted to start using this for my screenshots, but when I tried using the sxcu file for the images and  files part, I got a site not found error... Am I doing something wrong?

**Expected behavior**
To find the website

**ShareS Version**
4.5.3

**Screenshots**
Cant really take screenshots

**Desktop (please complete the following information):**
 - OS: Linux PopOS 20
 - Browser FireFox

**Additional context**
I am using sharenix, but configs should be the same as windows sharex

**Comment by somerandomcloud** [comment]
Nevermind, fixed it!

**Comment by xivade9146** [comment]
@somerandomcloud how did you get it to work?

**Comment by AzpektDev** [comment]
@somerandomcloud how have you fixed it?
