### ISSUE TITLE
Hosting Question

### ISSUE THREAD

**Issue by BasToTheMax** [TannerReynolds/ShareX-Upload-Server#68]
Can I use Pterodactyl Panel to host this? And can I use an custom port? (like `8100`)

**Comment by TheCuteFoxxy** [comment]
I am a shared hosting provider using pterodactyl panel and we host many ShareX servers.

You can use the custom port as long as you have a reverse proxy setup to point your domain to it.

**Comment by BasToTheMax** [comment]
Thx for your response :)
